// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package putmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMocked creates a new instance of MockMocked. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMocked(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMocked {
	mock := &MockMocked{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMocked is an autogenerated mock type for the Mocked type
type MockMocked struct {
	mock.Mock
}

type MockMocked_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMocked) EXPECT() *MockMocked_Expecter {
	return &MockMocked_Expecter{mock: &_m.Mock}
}

// Predicate provides a mock function for the type MockMocked
func (_mock *MockMocked) Predicate(context1 context.Context, v any) (bool, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for Predicate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (bool, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) bool); ok {
		r0 = returnFunc(context1, v)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMocked_Predicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Predicate'
type MockMocked_Predicate_Call struct {
	*mock.Call
}

// Predicate is a helper method to define mock.On call
//   - context1 context.Context
//   - v any
func (_e *MockMocked_Expecter) Predicate(context1 interface{}, v interface{}) *MockMocked_Predicate_Call {
	return &MockMocked_Predicate_Call{Call: _e.mock.On("Predicate", context1, v)}
}

func (_c *MockMocked_Predicate_Call) Run(run func(context1 context.Context, v any)) *MockMocked_Predicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMocked_Predicate_Call) Return(b bool, err error) *MockMocked_Predicate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMocked_Predicate_Call) RunAndReturn(run func(context1 context.Context, v any) (bool, error)) *MockMocked_Predicate_Call {
	_c.Call.Return(run)
	return _c
}
